services:
  mariadb:
    container_name: mariadb
    build:
      context: ./srcs/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    ports :
      - "3306:3306"
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: 
      context: ./srcs/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    expose : 
      - "9000"

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./srcs/nginx
    env_file:
      - .env
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/wordpress"

  mariadb:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/mariadb"
